export const NAV_ROUTES = {
  HOME: "/",
  PROFESSIONALS: "/professionals",
  BOOKINGS: "/bookings",
  CHAT: "/chat",
  PAYMENTS: "/payments",
  PROFILE: "/profile",
};

export const DASHBOARD_ROUTES = {
  ROOT: "/dashboard",
  PATIENT: "/dashboard/patient",
  PROFESSIONAL: "/dashboard/professional",
  ADMIN: "/dashboard/admin",
  ADMIN_USERS: "/dashboard/admin/users",
  ADMIN_VERIFICATION: "/dashboard/admin/verification",
  ADMIN_SERVICES: "/dashboard/admin/services",
  ADMIN_PROFESSIONALS: "/dashboard/admin/professionals",
  ADMIN_PATIENTS: "/dashboard/admin/patients",
  ADMIN_AUDIT: "/dashboard/admin/audit",
  ADMIN_CONSENT: "/dashboard/admin/consents",
  ADMIN_REJECT: "/dashboard/admin/rejects",
  PROFESSIONAL_AVAILABILITY: "/dashboard/professional/availability",
  PROFESSIONAL_SERVICES: "/dashboard/professional/services",
  PROFESSIONAL_PATIENTS: "/dashboard/professional/mypatients",
  PROFESSIONAL_CONSENT: "/dashboard/professional/consent",
  ADMIN_VERIFICATIONS: "/dashboard/admin/verification",
  NOTIFICATION_SETTINGS: "/dashboard/admin/notificationSettings",
  NOTIFICATIONS: "/dashboard/admin/notifications",
  CHAT_ROOMS: "/dashboard/admin/chatRooms",
  ADMIN_AVAILABILITY: "/dashboard/admin/availability",
  PAYMENTS: "/dashboard/admin/payments",
};
